project:
    title: ""
    type: website
    output-dir: _slides
    render:
        - presentation.qmd

author: "Timóteo Fassoni"
description: ""
lang: pt-BR

bibliography: room/references.bib
csl: https://www.zotero.org/styles/nature-brackets

format:
    revealjs:
        mainfont: "TeX Gyre Pagella"
        no-clean: true 
        theme:  default # Gostei: default , serif , simple
        logo: https://assets.tmfss.net/pos-seminar/IbitiLogo-3.svg
        css: "room/slides-theme.css"
        incrmental: true
        vcenter: true
        transition: slide
        slide-number: true
        chalkboard:
            buttons: true
        preview-links: auto
        html-math-method: mathjax
        include-in-header:
         - text: |
              <script>
              window.MathJax = {
                  loader: { load: ['[tex]/ams', 'output/chtml', 'ui/menu'] },
                  chtml: { font: 'mathjax-pagella' },
                  svg: { font: 'mathjax-pagella' }
                };
              </script>